<a href="https://colab.research.google.com/github/anonymous2184/data.ibuhamil.jawabarat/blob/main/UTS_Sisdas_Ghazy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

#membaca file
df = pd.read_csv('https://github.com/anonymous2184/data.ibuhamil.jawabarat/blob/main/dinkes-od_17485_jumlah_ibu_hamil_berdasarkan_kabupatenkota_v1_data.csv?raw=true')
df.head()

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_ibu_hamil,satuan,tahun
0,1,32,JAWA BARAT,3201,KABUPATEN BOGOR,126474,ORANG,2016
1,2,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,51056,ORANG,2016
2,3,32,JAWA BARAT,3203,KABUPATEN CIANJUR,46284,ORANG,2016
3,4,32,JAWA BARAT,3204,KABUPATEN BANDUNG,79912,ORANG,2016
4,5,32,JAWA BARAT,3205,KABUPATEN GARUT,62514,ORANG,2016

In [21]:
#mengecek data kosong
is_null = df.isnull().any().any()
print(is_null)

False

In [22]:
#memilih kolom yang digunakan
df.columns
selected_columns = ['id', 'kode_kabupaten_kota', 'nama_kabupaten_kota', 'jumlah_ibu_hamil','tahun']
selected_data = df.loc[:, selected_columns]
selected_data.head()

   id  kode_kabupaten_kota nama_kabupaten_kota  jumlah_ibu_hamil tahun
0   1                 3201     KABUPATEN BOGOR            126474  2016
1   2                 3202  KABUPATEN SUKABUMI             51056  2016
2   3                 3203   KABUPATEN CIANJUR             46284  2016
3   4                 3204   KABUPATEN BANDUNG             79912  2016
4   5                 3205     KABUPATEN GARUT             62514  2016

In [6]:
#mengubah tipe data
selected_data.dtypes

id                      int64
kode_kabupaten_kota     int64
nama_kabupaten_kota    object
jumlah_ibu_hamil        int64
tahun                   int64
dtype: object

In [23]:
selected_data['tahun'] = selected_data['tahun'].astype(str)
selected_data.dtypes

id                      int64
kode_kabupaten_kota     int64
nama_kabupaten_kota    object
jumlah_ibu_hamil        int64
tahun                  object
dtype: object

In [8]:
selected_data.columns

Index(['id', 'kode_kabupaten_kota', 'nama_kabupaten_kota', 'jumlah_ibu_hamil',
       'tahun'],
      dtype='object')

In [20]:
#mempersiapkan fitur dan target
features = selected_data['tahun'].values.reshape(-1,1)
target = selected_data['jumlah_ibu_hamil'].values

#normalisasi fitur
scaler = MinMaxScaler()
features = scaler.fit_transform(features)

#pembagian data pelatihan dan data pengujian
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.2, random_state=42)

#membuat model jst
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(1,)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error')

#pelatihan model
model.fit(features_train, target_train, epochs=50, batch_size=32, verbose=1)

#evaluasi model
loss = model.evaluate(features_test, target_test)
print("Mean Squared Error :", loss)

#prediksi tahun yang akan datang
tahun_datang = np.array([[2024]])
tahun_datang = scaler.transform(tahun_datang)
prediksi_ibu_hamil = model.predict(tahun_datang)
print("prediksi jumlah ibu hamil pada tahun 2024 :", prediksi_ibu_hamil)

Epoch 1/50

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1671779584.0000
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1607322496.0000
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1793602688.0000
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1741167360.0000
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1821004928.0000
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1933459072.0000
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1950251136.0000
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1788538368.0000
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1842048896.0000
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2028046592.0000
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1778614528.0000
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1743135488.0000
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1860223744.0000
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1864930816.0000
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1725371648.0000
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1802556288.0000
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1956369024.0000
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2040604544.0000
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1879788544.0000
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1888285056.0000
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1869392384.0000
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1757062400.0000
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1899532800.0000
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1973653888.0000
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1717099648.0000
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2037920384.0000
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1609800832.0000
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2111696000.0000
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2052174080.0000
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1591906944.0000
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1860342016.0000
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1763858432.0000
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1859508096.0000
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1821171456.0000
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1817016960.0000
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1986292608.0000
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1866561664.0000
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1851120896.0000
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1889495936.0000
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1905206144.0000
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1735507968.0000
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1758880896.0000
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1902055296.0000
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1902040576.0000
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1923916672.0000
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1782322688.0000
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1676411264.0000
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1887823616.0000
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1750208896.0000
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2155516928.0000
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2289588480.0000
Mean Squared Error : 2379515136.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
prediksi jumlah ibu hamil pada tahun 2024 : [[349.76144]]